DISTRO = "minimal"
DISTRO_NAME = "TezSign - built with love for the Tezos community by tez.capital"
DISTRO_VERSION = "1.0"

# 1. Enable systemd and usrmerge, remove sysvinit
DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES:remove = "sysvinit"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

# 2. Set systemd as the primary init manager
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

VIRTUAL-RUNTIME_base-utils = "toybox"
PREFERRED_PROVIDER_virtual/base-utils = "toybox"

USER_OVERRIDES += "${@'tezdev:' if d.getVar('TEZSIGN_DEV') == '1' else ''}"

PREFERRED_PROVIDER_virtual/sh = ""
PREFERRED_PROVIDER_virtual/sh:tezdev = "dash"

ALTERNATIVE_PRIORITY:pn-toybox = "100"
BAD_RECOMMENDATIONS += "busybox busybox-syslog busybox-udhcpc"
PACKAGE_EXCLUDE = "busybox"

KERNEL_MODULE_AUTOLOAD:append = " libcomposite"

USE_VT = "1"
TCLIBC = "musl"