name: build-host
description: Build the host application for the specified OS and architecture

inputs:
  image_id:
    required: true
    description: 'The ID of the artifact to build'
  source_artifact:
    required: true
    description: 'The source image to build from'
  create_binary_artifact:
    required: false
    description: 'Create tezsign_gadget_binary artifact'
    default: 'false'
  tezsign_flavour:
    description: 'TezSign flavour to build'
    required: false
    default: 'prod'

runs:
  using: "composite"
  steps:
  - name: Build docker image for reconfiguration
    shell: bash
    run: |
      sudo docker build -f tools/Containerfile -t tezsign/builder:latest .

  - name: Build builder
    shell: bash
    run: |
      sudo docker run -e CGO_ENABLED=0 --rm -v ${{ github.workspace }}/:/work tezsign/builder:latest go build -buildvcs=false -ldflags='-s -w -extldflags "-static"' -trimpath -o ./tools/bin/builder ./tools/builder

  - name: Build gadget
    shell: bash
    run: |
      sudo docker run -e GOOS=linux -e GOARCH=arm64 -e CGO_ENABLED=1 --rm -v ${{ github.workspace }}/:/work tezsign/builder:latest go build -buildvcs=false -ldflags='-s -w -extldflags "-static"' -trimpath -o ./tools/builder/assets/tezsign ./app/gadget

  - name: Build ffs_registrar
    shell: bash
    run: |
      sudo docker run -e GOOS=linux -e GOARCH=arm64 --rm -v ${{ github.workspace }}/:/work tezsign/builder:latest go build -buildvcs=false -ldflags='-s -w -extldflags "-static"' -trimpath -o ./tools/builder/assets/ffs_registrar ./app/ffs_registrar

  # we download images only after build not to spend time downloading if build fails
  - name: Download base image
    uses: actions/download-artifact@v5
    with:
      name: ${{ inputs.source_artifact }}
      path: ./imgs

  - name: List images dir
    shell: bash
    run: ls -la ./imgs

  - name: Reconfigure to dev image
    if: ${{ inputs.tezsign_flavour == 'dev' }}
    shell: bash
    env:
      IMAGE_ID: ${{ inputs.image_id }}.dev
    run: |
      sudo docker run -e $IMAGE_ID -e CGO_ENABLED=0 --rm --privileged -v ${{ github.workspace }}/:/work tezsign/builder:latest ./tools/bin/builder ./imgs/${{ inputs.source_artifact }}.img ./imgs/${{ inputs.image_id }}.dev.img.xz dev

  - name: Reconfigure to prod image
    if: ${{ inputs.tezsign_flavour == 'prod' }}
    shell: bash
    env:
      IMAGE_ID: ${{ inputs.image_id }}
    run: |
      sudo docker run -e $IMAGE_ID -e CGO_ENABLED=0 --rm --privileged -v ${{ github.workspace }}/:/work tezsign/builder:latest ./tools/bin/builder ./imgs/${{ inputs.source_artifact }}.img ./imgs/${{ inputs.image_id }}.img.xz prod

  - uses: actions/upload-artifact@v5
    if: ${{ inputs.tezsign_flavour == 'prod' }}
    with:
      name: ${{ inputs.image_id }}.img.xz
      path: ${{ github.workspace }}/imgs/${{ inputs.image_id }}.img.xz
      retention-days: 1

  - uses: actions/upload-artifact@v5  
    if: ${{ inputs.tezsign_flavour == 'dev' }}
    with:
      name: ${{ inputs.image_id }}.dev.img.xz
      path: ${{ github.workspace }}/imgs/${{ inputs.image_id }}.dev.img.xz
      retention-days: 1

  - name: Copy tezsign for upload
    shell: bash
    run: |
      cp ./tools/builder/assets/tezsign ./tezsign-gadget-binary
  - uses: actions/upload-artifact@v5
    if: ${{ inputs.create_binary_artifact == 'true' }}
    with:
      name: tezsign_gadget_binary
      path: ./tezsign-gadget-binary
      retention-days: 1