include conf/machine/raspberrypi0-2w-64.conf

PREFERRED_PROVIDER_virtual/kernel = "linux-mainline"
PREFERRED_VERSION_linux-mainline ?= "6.18+git"
RPI_KERNEL_DEVICETREE_OVERLAYS = ""
RPI_KERNEL_DEVICETREE = "broadcom/bcm2837-rpi-zero-2-w.dtb"
DISABLE_VC4GRAPHICS = "1"
SERIAL_CONSOLES = "115200;ttyS1"
RPI_EXTRA_IMAGE_BOOT_FILES = " \
    ${@bb.utils.contains('INITRAMFS_IMAGE_BUNDLE', '1', '${KERNEL_IMAGETYPE}-${INITRAMFS_LINK_NAME}.bin;${SDIMG_KERNELIMAGE}', '${KERNEL_IMAGETYPE};${SDIMG_KERNELIMAGE}', d)} \
"

IMAGE_BOOT_FILES:remove = "${BOOTFILES_DIR_NAME}/*"
IMAGE_BOOT_FILES:append = " \
    ${BOOTFILES_DIR_NAME}/bootcode.bin;bootcode.bin \
    ${BOOTFILES_DIR_NAME}/start.elf;start.elf \
    ${BOOTFILES_DIR_NAME}/fixup.dat;fixup.dat \
    ${BOOTFILES_DIR_NAME}/config.txt;config.txt \
    ${BOOTFILES_DIR_NAME}/cmdline.txt;cmdline.txt \
"
