include conf/machine/raspberrypi4-64.conf

PREFERRED_PROVIDER_virtual/kernel = "linux-mainline"
PREFERRED_VERSION_linux-mainline ?= "6.18%"
RPI_KERNEL_DEVICETREE_OVERLAYS = ""
RPI_KERNEL_DEVICETREE = "broadcom/bcm2711-rpi-4-b.dtb"
DISABLE_VC4GRAPHICS = "1"
SERIAL_CONSOLES = "115200;ttyS1"

IMAGE_BOOT_FILES:remove = "${BOOTFILES_DIR_NAME}/*"
IMAGE_BOOT_FILES:append = " \
    ${BOOTFILES_DIR_NAME}/*.elf \
    ${BOOTFILES_DIR_NAME}/*.dat \
    ${BOOTFILES_DIR_NAME}/*.bin \
    ${BOOTFILES_DIR_NAME}/config.txt;config.txt \
    ${BOOTFILES_DIR_NAME}/cmdline.txt;cmdline.txt \
    overlay_map.dtb;overlays/overlay_map.dtb \
    dwc2.dtbo;overlays/dwc2.dtbo \
"
