header:
  version: 14

distro: minimal
target: minimal-image

repos:
  poky:
    url: git://git.yoctoproject.org/poky.git
    branch: "scarthgap"
    layers:
      meta:
      meta-poky:
  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi
    branch: "scarthgap"
  meta-tezsign:
    path: meta-tezsign
  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded.git
    branch: "scarthgap"
    layers:
      meta-oe: # This is where 'dash' lives


local_conf_header:
  # initramfs_setup: |
  #   # Define the image type required for initramfs
  #   IMAGE_FSTYPES = "cpio.gz"
    
  #   # Bundle the initramfs into the kernel image (zImage/uImage)
  #   INITRAMFS_IMAGE = "core-image-base"
  #   INITRAMFS_IMAGE_BUNDLE = "1"

  #   CMDLINE_ROOTFS = "root=/dev/ram0 rw rootfstype=ramfs rootwait rdinit=/init"

  speed_and_cache: |
    # Tell Git to only download the latest snapshot, not the 20-year history
    BB_GIT_SHALLOW = "1"
    
    # Use Yocto's high-speed source mirrors before trying the main servers
    SOURCE_MIRROR_URL = "http://downloads.yoctoproject.org/mirror/sources/"
    INHERIT += "own-mirrors"
    
    # Save downloads outside the build folder so they survive a clean rebuild
    DL_DIR = "${TOPDIR}/../downloads"

  licenses: |
    LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"