name: build-host
description: Build the host application for the specified OS and architecture

inputs:
  artifact-id:
    required: true
    description: 'The ID of the artifact to build'
  goos:
    description: 'The GOOS value for the build'
    required: true
  goarch:
    description: 'The GOARCH value for the build'
    required: true
  libusb-host:
    required: true
    description: 'The libusb host target'

runs:
  using: "composite"
  steps:
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: '>=1.26.0'

  - name: Create build dir
    shell: bash
    run: mkdir -p build

  - name: Install dev tools
    shell: bash
    run: |
      brew install autoconf automake libtool pkg-config

  - name: autogen libusb (macos)
    shell: bash
    working-directory: ${{ github.workspace }}/libs/libusb
    run: ./autogen.sh --disable-udev --host=${{ inputs.libusb-host }}

  - name: configure libusb (macos)
    shell: bash
    env:
      INSTALL_DIR: ${{ github.workspace }}/libs/.install
    working-directory: ${{ github.workspace }}/libs/libusb
    run: ./configure --prefix=$INSTALL_DIR --enable-udev=no --enable-shared=no --disable-dependency-tracking --host=${{ inputs.libusb-host }}

  - name: make libusb
    shell: bash
    working-directory: ${{ github.workspace }}/libs/libusb
    run: make install

  - name: Build host (macos)
    shell: bash
    env:
      CGO_ENABLED: 1
      PKG_CONFIG_PATH: "${{ github.workspace }}/libs/.install/lib/pkgconfig"
    run: |
       go build -ldflags='-s -w -extldflags "-I${{ github.workspace }}/libs/.install/include/libusb-1.0 -L${{ github.workspace }}/libs/.install/lib/ -lusb-1.0 -framework IOKit -framework CoreFoundation -framework Security"' -trimpath -o ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }} ./app/host

  - uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact-id }}
      path: ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }}
      retention-days: 1
