BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-gadget"
BBFILE_PATTERN_meta-gadget = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-gadget = "10"

# Change 'rpi' to 'raspberrypi'
LAYERDEPENDS_meta-gadget = "core raspberrypi"
LAYERSERIES_COMPAT_meta-gadget = "scarthgap"

PACKAGECONFIG:remove:pn-systemd = " \
    networkd resolved timesyncd nss-resolve \
    acl bluez dbus elfutils idn locale \
    manpages polkit seccomp xkbcommon \
"

IMAGE_LINGUAS = ""
FORCE_RO_REMOVE = "1"
NO_RECOMMENDATIONS = "1"