# conf/distro/tezsign.conf

# Inherit the absolute bare minimum metadata (compilers, basic bitbake rules)
require conf/distro/poky.conf

DISTRO = "tezsign"
DISTRO_NAME = "Tezsign"
DISTRO_VERSION = "1.0"

# ------------------------------------------------------------------
# THE OPT-IN APPROACH: OVERWRITE THE DEFAULTS COMPLETELY
# ------------------------------------------------------------------
# By using '=' instead of 'append', we wipe out Poky's massive list 
# and start from zero. We only add exactly what we need.

DISTRO_FEATURES = " \
    systemd \
    usrmerge \
    usbgadget \
"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RDEPENDS = ""

# Set systemd as the absolute default across the OS
INIT_MANAGER = "systemd"

# Disable Native Language Support globally
USE_NLS = "no"

# (Optional) Use a smaller C library if you want to get extreme, 
# though glibc is usually fine if you have 512MB RAM.
# TCLIBC = "musl"