// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: signer.proto

package signer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- status ----
type LockState int32

const (
	LockState_LOCK_STATE_UNSPECIFIED LockState = 0
	LockState_LOCKED                 LockState = 1
	LockState_UNLOCKED               LockState = 2
)

// Enum value maps for LockState.
var (
	LockState_name = map[int32]string{
		0: "LOCK_STATE_UNSPECIFIED",
		1: "LOCKED",
		2: "UNLOCKED",
	}
	LockState_value = map[string]int32{
		"LOCK_STATE_UNSPECIFIED": 0,
		"LOCKED":                 1,
		"UNLOCKED":               2,
	}
)

func (x LockState) Enum() *LockState {
	p := new(LockState)
	*p = x
	return p
}

func (x LockState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockState) Descriptor() protoreflect.EnumDescriptor {
	return file_signer_proto_enumTypes[0].Descriptor()
}

func (LockState) Type() protoreflect.EnumType {
	return &file_signer_proto_enumTypes[0]
}

func (x LockState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockState.Descriptor instead.
func (LockState) EnumDescriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{0}
}

type PerKeyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerKeyResult) Reset() {
	*x = PerKeyResult{}
	mi := &file_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerKeyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerKeyResult) ProtoMessage() {}

func (x *PerKeyResult) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerKeyResult.ProtoReflect.Descriptor instead.
func (*PerKeyResult) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{0}
}

func (x *PerKeyResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PerKeyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PerKeyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---- unlock ----
type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIds        []string               `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	Passphrase    []byte                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{1}
}

func (x *UnlockRequest) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *UnlockRequest) GetPassphrase() []byte {
	if x != nil {
		return x.Passphrase
	}
	return nil
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PerKeyResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{2}
}

func (x *UnlockResponse) GetResults() []*PerKeyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// ---- lock ----
type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIds        []string               `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{3}
}

func (x *LockRequest) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PerKeyResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{4}
}

func (x *LockResponse) GetResults() []*PerKeyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type KeyStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	KeyId                   string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	LockState               LockState              `protobuf:"varint,2,opt,name=lock_state,json=lockState,proto3,enum=signer.LockState" json:"lock_state,omitempty"` // true if key is unlocked in memory
	Tz4                     string                 `protobuf:"bytes,3,opt,name=tz4,proto3" json:"tz4,omitempty"`                                                     // tz4 address (always available)
	BlPubkey                string                 `protobuf:"bytes,4,opt,name=bl_pubkey,json=blPubkey,proto3" json:"bl_pubkey,omitempty"`                           // BLpk… (always available)
	Pop                     string                 `protobuf:"bytes,5,opt,name=pop,proto3" json:"pop,omitempty"`                                                     // BLsig… PoP over pubkey (always available)
	LastBlockLevel          uint64                 `protobuf:"varint,10,opt,name=last_block_level,json=lastBlockLevel,proto3" json:"last_block_level,omitempty"`
	LastPreattestationLevel uint64                 `protobuf:"varint,11,opt,name=last_preattestation_level,json=lastPreattestationLevel,proto3" json:"last_preattestation_level,omitempty"`
	LastAttestationLevel    uint64                 `protobuf:"varint,12,opt,name=last_attestation_level,json=lastAttestationLevel,proto3" json:"last_attestation_level,omitempty"`
	LastBlockRound          uint32                 `protobuf:"varint,20,opt,name=last_block_round,json=lastBlockRound,proto3" json:"last_block_round,omitempty"`
	LastPreattestationRound uint32                 `protobuf:"varint,21,opt,name=last_preattestation_round,json=lastPreattestationRound,proto3" json:"last_preattestation_round,omitempty"`
	LastAttestationRound    uint32                 `protobuf:"varint,22,opt,name=last_attestation_round,json=lastAttestationRound,proto3" json:"last_attestation_round,omitempty"`
	StateCorrupted          bool                   `protobuf:"varint,30,opt,name=state_corrupted,json=stateCorrupted,proto3" json:"state_corrupted,omitempty"` // true if level.bin failed to decrypt/load
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *KeyStatus) Reset() {
	*x = KeyStatus{}
	mi := &file_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyStatus) ProtoMessage() {}

func (x *KeyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyStatus.ProtoReflect.Descriptor instead.
func (*KeyStatus) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{5}
}

func (x *KeyStatus) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyStatus) GetLockState() LockState {
	if x != nil {
		return x.LockState
	}
	return LockState_LOCK_STATE_UNSPECIFIED
}

func (x *KeyStatus) GetTz4() string {
	if x != nil {
		return x.Tz4
	}
	return ""
}

func (x *KeyStatus) GetBlPubkey() string {
	if x != nil {
		return x.BlPubkey
	}
	return ""
}

func (x *KeyStatus) GetPop() string {
	if x != nil {
		return x.Pop
	}
	return ""
}

func (x *KeyStatus) GetLastBlockLevel() uint64 {
	if x != nil {
		return x.LastBlockLevel
	}
	return 0
}

func (x *KeyStatus) GetLastPreattestationLevel() uint64 {
	if x != nil {
		return x.LastPreattestationLevel
	}
	return 0
}

func (x *KeyStatus) GetLastAttestationLevel() uint64 {
	if x != nil {
		return x.LastAttestationLevel
	}
	return 0
}

func (x *KeyStatus) GetLastBlockRound() uint32 {
	if x != nil {
		return x.LastBlockRound
	}
	return 0
}

func (x *KeyStatus) GetLastPreattestationRound() uint32 {
	if x != nil {
		return x.LastPreattestationRound
	}
	return 0
}

func (x *KeyStatus) GetLastAttestationRound() uint32 {
	if x != nil {
		return x.LastAttestationRound
	}
	return 0
}

func (x *KeyStatus) GetStateCorrupted() bool {
	if x != nil {
		return x.StateCorrupted
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_signer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyStatus           `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_signer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetKeys() []*KeyStatus {
	if x != nil {
		return x.Keys
	}
	return nil
}

// ---- sign ----
// Gadget decodes raw bytes to determine both.
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tz4           string                 `protobuf:"bytes,1,opt,name=tz4,proto3" json:"tz4,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // raw, encoded Tezos content to sign
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_signer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{8}
}

func (x *SignRequest) GetTz4() string {
	if x != nil {
		return x.Tz4
	}
	return ""
}

func (x *SignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // compressed BLsig (96B)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_signer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{9}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ---- new keys ----
type NewKeyPerKeyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`          // final id (auto or requested)
	BlPubkey      string                 `protobuf:"bytes,2,opt,name=bl_pubkey,json=blPubkey,proto3" json:"bl_pubkey,omitempty"` // Base58 BLPubkey
	Tz4           string                 `protobuf:"bytes,3,opt,name=tz4,proto3" json:"tz4,omitempty"`                           // tz4 hash of pubkey
	Ok            bool                   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKeyPerKeyResult) Reset() {
	*x = NewKeyPerKeyResult{}
	mi := &file_signer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKeyPerKeyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKeyPerKeyResult) ProtoMessage() {}

func (x *NewKeyPerKeyResult) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKeyPerKeyResult.ProtoReflect.Descriptor instead.
func (*NewKeyPerKeyResult) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{10}
}

func (x *NewKeyPerKeyResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *NewKeyPerKeyResult) GetBlPubkey() string {
	if x != nil {
		return x.BlPubkey
	}
	return ""
}

func (x *NewKeyPerKeyResult) GetTz4() string {
	if x != nil {
		return x.Tz4
	}
	return ""
}

func (x *NewKeyPerKeyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NewKeyPerKeyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NewKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: provide one or more aliases
	// If empty, gadget auto-assigns (e.g., "key3").
	KeyIds        []string `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	Passphrase    []byte   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKeysRequest) Reset() {
	*x = NewKeysRequest{}
	mi := &file_signer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKeysRequest) ProtoMessage() {}

func (x *NewKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKeysRequest.ProtoReflect.Descriptor instead.
func (*NewKeysRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{11}
}

func (x *NewKeysRequest) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *NewKeysRequest) GetPassphrase() []byte {
	if x != nil {
		return x.Passphrase
	}
	return nil
}

type NewKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One result per attempted key (includes ok/error + key material)
	Results       []*NewKeyPerKeyResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKeysResponse) Reset() {
	*x = NewKeysResponse{}
	mi := &file_signer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKeysResponse) ProtoMessage() {}

func (x *NewKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKeysResponse.ProtoReflect.Descriptor instead.
func (*NewKeysResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{12}
}

func (x *NewKeysResponse) GetResults() []*NewKeyPerKeyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// ---- logs ----
type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max number of most-recent log lines to return.
	// If zero, gadget picks a sensible default (e.g., 100).
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_signer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{13}
}

func (x *LogsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"` // newest last
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_signer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{14}
}

func (x *LogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

// ---- init master ----
type InitMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deterministic bool                   `protobuf:"varint,1,opt,name=deterministic,proto3" json:"deterministic,omitempty"` // true => HD mode; false => random-only mode
	Passphrase    []byte                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`        // used to derive KEK and encrypt seed.bin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMasterRequest) Reset() {
	*x = InitMasterRequest{}
	mi := &file_signer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMasterRequest) ProtoMessage() {}

func (x *InitMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMasterRequest.ProtoReflect.Descriptor instead.
func (*InitMasterRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{15}
}

func (x *InitMasterRequest) GetDeterministic() bool {
	if x != nil {
		return x.Deterministic
	}
	return false
}

func (x *InitMasterRequest) GetPassphrase() []byte {
	if x != nil {
		return x.Passphrase
	}
	return nil
}

// ---- init master info ----
type InitInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitInfoRequest) Reset() {
	*x = InitInfoRequest{}
	mi := &file_signer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitInfoRequest) ProtoMessage() {}

func (x *InitInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitInfoRequest.ProtoReflect.Descriptor instead.
func (*InitInfoRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{16}
}

type InitInfoResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MasterPresent        bool                   `protobuf:"varint,1,opt,name=master_present,json=masterPresent,proto3" json:"master_present,omitempty"`                      // master.json exists
	DeterministicEnabled bool                   `protobuf:"varint,2,opt,name=deterministic_enabled,json=deterministicEnabled,proto3" json:"deterministic_enabled,omitempty"` // first byte of seed.bin == 0x01 (only meaningful if seed_present==true)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitInfoResponse) Reset() {
	*x = InitInfoResponse{}
	mi := &file_signer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitInfoResponse) ProtoMessage() {}

func (x *InitInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitInfoResponse.ProtoReflect.Descriptor instead.
func (*InitInfoResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{17}
}

func (x *InitInfoResponse) GetMasterPresent() bool {
	if x != nil {
		return x.MasterPresent
	}
	return false
}

func (x *InitInfoResponse) GetDeterministicEnabled() bool {
	if x != nil {
		return x.DeterministicEnabled
	}
	return false
}

// ---- set level ----
// When executed, round is reset to zero on disk.
type SetLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Level         uint64                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLevelRequest) Reset() {
	*x = SetLevelRequest{}
	mi := &file_signer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLevelRequest) ProtoMessage() {}

func (x *SetLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLevelRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{18}
}

func (x *SetLevelRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SetLevelRequest) GetLevel() uint64 {
	if x != nil {
		return x.Level
	}
	return 0
}

// ---- delete keys ----
type DeleteKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIds        []string               `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	Passphrase    []byte                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeysRequest) Reset() {
	*x = DeleteKeysRequest{}
	mi := &file_signer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeysRequest) ProtoMessage() {}

func (x *DeleteKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeysRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeysRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteKeysRequest) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *DeleteKeysRequest) GetPassphrase() []byte {
	if x != nil {
		return x.Passphrase
	}
	return nil
}

type DeleteKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PerKeyResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeysResponse) Reset() {
	*x = DeleteKeysResponse{}
	mi := &file_signer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeysResponse) ProtoMessage() {}

func (x *DeleteKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeysResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeysResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteKeysResponse) GetResults() []*PerKeyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_signer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{21}
}

func (x *Ok) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_signer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{22}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Unlock
	//	*Request_Lock
	//	*Request_Status
	//	*Request_Sign
	//	*Request_NewKeys
	//	*Request_Logs
	//	*Request_InitMaster
	//	*Request_InitInfo
	//	*Request_SetLevel
	//	*Request_DeleteKeys
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_signer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{23}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetUnlock() *UnlockRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Unlock); ok {
			return x.Unlock
		}
	}
	return nil
}

func (x *Request) GetLock() *LockRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Lock); ok {
			return x.Lock
		}
	}
	return nil
}

func (x *Request) GetStatus() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Request) GetSign() *SignRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Sign); ok {
			return x.Sign
		}
	}
	return nil
}

func (x *Request) GetNewKeys() *NewKeysRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_NewKeys); ok {
			return x.NewKeys
		}
	}
	return nil
}

func (x *Request) GetLogs() *LogsRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *Request) GetInitMaster() *InitMasterRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_InitMaster); ok {
			return x.InitMaster
		}
	}
	return nil
}

func (x *Request) GetInitInfo() *InitInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_InitInfo); ok {
			return x.InitInfo
		}
	}
	return nil
}

func (x *Request) GetSetLevel() *SetLevelRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_SetLevel); ok {
			return x.SetLevel
		}
	}
	return nil
}

func (x *Request) GetDeleteKeys() *DeleteKeysRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_DeleteKeys); ok {
			return x.DeleteKeys
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Unlock struct {
	Unlock *UnlockRequest `protobuf:"bytes,1,opt,name=unlock,proto3,oneof"`
}

type Request_Lock struct {
	Lock *LockRequest `protobuf:"bytes,2,opt,name=lock,proto3,oneof"`
}

type Request_Status struct {
	Status *StatusRequest `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type Request_Sign struct {
	Sign *SignRequest `protobuf:"bytes,4,opt,name=sign,proto3,oneof"`
}

type Request_NewKeys struct {
	NewKeys *NewKeysRequest `protobuf:"bytes,5,opt,name=new_keys,json=newKeys,proto3,oneof"`
}

type Request_Logs struct {
	Logs *LogsRequest `protobuf:"bytes,6,opt,name=logs,proto3,oneof"`
}

type Request_InitMaster struct {
	InitMaster *InitMasterRequest `protobuf:"bytes,7,opt,name=init_master,json=initMaster,proto3,oneof"`
}

type Request_InitInfo struct {
	InitInfo *InitInfoRequest `protobuf:"bytes,8,opt,name=init_info,json=initInfo,proto3,oneof"`
}

type Request_SetLevel struct {
	SetLevel *SetLevelRequest `protobuf:"bytes,9,opt,name=set_level,json=setLevel,proto3,oneof"`
}

type Request_DeleteKeys struct {
	DeleteKeys *DeleteKeysRequest `protobuf:"bytes,10,opt,name=delete_keys,json=deleteKeys,proto3,oneof"`
}

func (*Request_Unlock) isRequest_Payload() {}

func (*Request_Lock) isRequest_Payload() {}

func (*Request_Status) isRequest_Payload() {}

func (*Request_Sign) isRequest_Payload() {}

func (*Request_NewKeys) isRequest_Payload() {}

func (*Request_Logs) isRequest_Payload() {}

func (*Request_InitMaster) isRequest_Payload() {}

func (*Request_InitInfo) isRequest_Payload() {}

func (*Request_SetLevel) isRequest_Payload() {}

func (*Request_DeleteKeys) isRequest_Payload() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Unlock
	//	*Response_Lock
	//	*Response_Status
	//	*Response_Sign
	//	*Response_NewKey
	//	*Response_Logs
	//	*Response_InitInfo
	//	*Response_DeleteKeys
	//	*Response_Ok
	//	*Response_Error
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_signer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{24}
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetUnlock() *UnlockResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Unlock); ok {
			return x.Unlock
		}
	}
	return nil
}

func (x *Response) GetLock() *LockResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Lock); ok {
			return x.Lock
		}
	}
	return nil
}

func (x *Response) GetStatus() *StatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Response) GetSign() *SignResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Sign); ok {
			return x.Sign
		}
	}
	return nil
}

func (x *Response) GetNewKey() *NewKeysResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_NewKey); ok {
			return x.NewKey
		}
	}
	return nil
}

func (x *Response) GetLogs() *LogsResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *Response) GetInitInfo() *InitInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_InitInfo); ok {
			return x.InitInfo
		}
	}
	return nil
}

func (x *Response) GetDeleteKeys() *DeleteKeysResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_DeleteKeys); ok {
			return x.DeleteKeys
		}
	}
	return nil
}

func (x *Response) GetOk() *Ok {
	if x != nil {
		if x, ok := x.Payload.(*Response_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Unlock struct {
	Unlock *UnlockResponse `protobuf:"bytes,1,opt,name=unlock,proto3,oneof"`
}

type Response_Lock struct {
	Lock *LockResponse `protobuf:"bytes,2,opt,name=lock,proto3,oneof"`
}

type Response_Status struct {
	Status *StatusResponse `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type Response_Sign struct {
	Sign *SignResponse `protobuf:"bytes,4,opt,name=sign,proto3,oneof"`
}

type Response_NewKey struct {
	NewKey *NewKeysResponse `protobuf:"bytes,5,opt,name=new_key,json=newKey,proto3,oneof"`
}

type Response_Logs struct {
	Logs *LogsResponse `protobuf:"bytes,6,opt,name=logs,proto3,oneof"`
}

type Response_InitInfo struct {
	InitInfo *InitInfoResponse `protobuf:"bytes,7,opt,name=init_info,json=initInfo,proto3,oneof"`
}

type Response_DeleteKeys struct {
	DeleteKeys *DeleteKeysResponse `protobuf:"bytes,8,opt,name=delete_keys,json=deleteKeys,proto3,oneof"`
}

type Response_Ok struct {
	Ok *Ok `protobuf:"bytes,15,opt,name=ok,proto3,oneof"` // for init_master & set_level
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

func (*Response_Unlock) isResponse_Payload() {}

func (*Response_Lock) isResponse_Payload() {}

func (*Response_Status) isResponse_Payload() {}

func (*Response_Sign) isResponse_Payload() {}

func (*Response_NewKey) isResponse_Payload() {}

func (*Response_Logs) isResponse_Payload() {}

func (*Response_InitInfo) isResponse_Payload() {}

func (*Response_DeleteKeys) isResponse_Payload() {}

func (*Response_Ok) isResponse_Payload() {}

func (*Response_Error) isResponse_Payload() {}

var File_signer_proto protoreflect.FileDescriptor

const file_signer_proto_rawDesc = "" +
	"\n" +
	"\fsigner.proto\x12\x06signer\"K\n" +
	"\fPerKeyResult\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"H\n" +
	"\rUnlockRequest\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\fR\n" +
	"passphrase\"@\n" +
	"\x0eUnlockResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.signer.PerKeyResultR\aresults\"&\n" +
	"\vLockRequest\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\">\n" +
	"\fLockResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.signer.PerKeyResultR\aresults\"\xf6\x03\n" +
	"\tKeyStatus\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x120\n" +
	"\n" +
	"lock_state\x18\x02 \x01(\x0e2\x11.signer.LockStateR\tlockState\x12\x10\n" +
	"\x03tz4\x18\x03 \x01(\tR\x03tz4\x12\x1b\n" +
	"\tbl_pubkey\x18\x04 \x01(\tR\bblPubkey\x12\x10\n" +
	"\x03pop\x18\x05 \x01(\tR\x03pop\x12(\n" +
	"\x10last_block_level\x18\n" +
	" \x01(\x04R\x0elastBlockLevel\x12:\n" +
	"\x19last_preattestation_level\x18\v \x01(\x04R\x17lastPreattestationLevel\x124\n" +
	"\x16last_attestation_level\x18\f \x01(\x04R\x14lastAttestationLevel\x12(\n" +
	"\x10last_block_round\x18\x14 \x01(\rR\x0elastBlockRound\x12:\n" +
	"\x19last_preattestation_round\x18\x15 \x01(\rR\x17lastPreattestationRound\x124\n" +
	"\x16last_attestation_round\x18\x16 \x01(\rR\x14lastAttestationRound\x12'\n" +
	"\x0fstate_corrupted\x18\x1e \x01(\bR\x0estateCorrupted\"\x0f\n" +
	"\rStatusRequest\"7\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x04keys\x18\x01 \x03(\v2\x11.signer.KeyStatusR\x04keys\"9\n" +
	"\vSignRequest\x12\x10\n" +
	"\x03tz4\x18\x01 \x01(\tR\x03tz4\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\x80\x01\n" +
	"\x12NewKeyPerKeyResult\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1b\n" +
	"\tbl_pubkey\x18\x02 \x01(\tR\bblPubkey\x12\x10\n" +
	"\x03tz4\x18\x03 \x01(\tR\x03tz4\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"I\n" +
	"\x0eNewKeysRequest\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\fR\n" +
	"passphrase\"G\n" +
	"\x0fNewKeysResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.signer.NewKeyPerKeyResultR\aresults\"#\n" +
	"\vLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"$\n" +
	"\fLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"Y\n" +
	"\x11InitMasterRequest\x12$\n" +
	"\rdeterministic\x18\x01 \x01(\bR\rdeterministic\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\fR\n" +
	"passphrase\"\x11\n" +
	"\x0fInitInfoRequest\"n\n" +
	"\x10InitInfoResponse\x12%\n" +
	"\x0emaster_present\x18\x01 \x01(\bR\rmasterPresent\x123\n" +
	"\x15deterministic_enabled\x18\x02 \x01(\bR\x14deterministicEnabled\">\n" +
	"\x0fSetLevelRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x04R\x05level\"L\n" +
	"\x11DeleteKeysRequest\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\fR\n" +
	"passphrase\"D\n" +
	"\x12DeleteKeysResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.signer.PerKeyResultR\aresults\"\x14\n" +
	"\x02Ok\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x04\n" +
	"\aRequest\x12/\n" +
	"\x06unlock\x18\x01 \x01(\v2\x15.signer.UnlockRequestH\x00R\x06unlock\x12)\n" +
	"\x04lock\x18\x02 \x01(\v2\x13.signer.LockRequestH\x00R\x04lock\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x15.signer.StatusRequestH\x00R\x06status\x12)\n" +
	"\x04sign\x18\x04 \x01(\v2\x13.signer.SignRequestH\x00R\x04sign\x123\n" +
	"\bnew_keys\x18\x05 \x01(\v2\x16.signer.NewKeysRequestH\x00R\anewKeys\x12)\n" +
	"\x04logs\x18\x06 \x01(\v2\x13.signer.LogsRequestH\x00R\x04logs\x12<\n" +
	"\vinit_master\x18\a \x01(\v2\x19.signer.InitMasterRequestH\x00R\n" +
	"initMaster\x126\n" +
	"\tinit_info\x18\b \x01(\v2\x17.signer.InitInfoRequestH\x00R\binitInfo\x126\n" +
	"\tset_level\x18\t \x01(\v2\x17.signer.SetLevelRequestH\x00R\bsetLevel\x12<\n" +
	"\vdelete_keys\x18\n" +
	" \x01(\v2\x19.signer.DeleteKeysRequestH\x00R\n" +
	"deleteKeysB\t\n" +
	"\apayload\"\xee\x03\n" +
	"\bResponse\x120\n" +
	"\x06unlock\x18\x01 \x01(\v2\x16.signer.UnlockResponseH\x00R\x06unlock\x12*\n" +
	"\x04lock\x18\x02 \x01(\v2\x14.signer.LockResponseH\x00R\x04lock\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x16.signer.StatusResponseH\x00R\x06status\x12*\n" +
	"\x04sign\x18\x04 \x01(\v2\x14.signer.SignResponseH\x00R\x04sign\x122\n" +
	"\anew_key\x18\x05 \x01(\v2\x17.signer.NewKeysResponseH\x00R\x06newKey\x12*\n" +
	"\x04logs\x18\x06 \x01(\v2\x14.signer.LogsResponseH\x00R\x04logs\x127\n" +
	"\tinit_info\x18\a \x01(\v2\x18.signer.InitInfoResponseH\x00R\binitInfo\x12=\n" +
	"\vdelete_keys\x18\b \x01(\v2\x1a.signer.DeleteKeysResponseH\x00R\n" +
	"deleteKeys\x12\x1c\n" +
	"\x02ok\x18\x0f \x01(\v2\n" +
	".signer.OkH\x00R\x02ok\x12%\n" +
	"\x05error\x18\x10 \x01(\v2\r.signer.ErrorH\x00R\x05errorB\t\n" +
	"\apayload*A\n" +
	"\tLockState\x12\x1a\n" +
	"\x16LOCK_STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06LOCKED\x10\x01\x12\f\n" +
	"\bUNLOCKED\x10\x02B\x11Z\x0f./signer;signerb\x06proto3"

var (
	file_signer_proto_rawDescOnce sync.Once
	file_signer_proto_rawDescData []byte
)

func file_signer_proto_rawDescGZIP() []byte {
	file_signer_proto_rawDescOnce.Do(func() {
		file_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)))
	})
	return file_signer_proto_rawDescData
}

var file_signer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_signer_proto_goTypes = []any{
	(LockState)(0),             // 0: signer.LockState
	(*PerKeyResult)(nil),       // 1: signer.PerKeyResult
	(*UnlockRequest)(nil),      // 2: signer.UnlockRequest
	(*UnlockResponse)(nil),     // 3: signer.UnlockResponse
	(*LockRequest)(nil),        // 4: signer.LockRequest
	(*LockResponse)(nil),       // 5: signer.LockResponse
	(*KeyStatus)(nil),          // 6: signer.KeyStatus
	(*StatusRequest)(nil),      // 7: signer.StatusRequest
	(*StatusResponse)(nil),     // 8: signer.StatusResponse
	(*SignRequest)(nil),        // 9: signer.SignRequest
	(*SignResponse)(nil),       // 10: signer.SignResponse
	(*NewKeyPerKeyResult)(nil), // 11: signer.NewKeyPerKeyResult
	(*NewKeysRequest)(nil),     // 12: signer.NewKeysRequest
	(*NewKeysResponse)(nil),    // 13: signer.NewKeysResponse
	(*LogsRequest)(nil),        // 14: signer.LogsRequest
	(*LogsResponse)(nil),       // 15: signer.LogsResponse
	(*InitMasterRequest)(nil),  // 16: signer.InitMasterRequest
	(*InitInfoRequest)(nil),    // 17: signer.InitInfoRequest
	(*InitInfoResponse)(nil),   // 18: signer.InitInfoResponse
	(*SetLevelRequest)(nil),    // 19: signer.SetLevelRequest
	(*DeleteKeysRequest)(nil),  // 20: signer.DeleteKeysRequest
	(*DeleteKeysResponse)(nil), // 21: signer.DeleteKeysResponse
	(*Ok)(nil),                 // 22: signer.Ok
	(*Error)(nil),              // 23: signer.Error
	(*Request)(nil),            // 24: signer.Request
	(*Response)(nil),           // 25: signer.Response
}
var file_signer_proto_depIdxs = []int32{
	1,  // 0: signer.UnlockResponse.results:type_name -> signer.PerKeyResult
	1,  // 1: signer.LockResponse.results:type_name -> signer.PerKeyResult
	0,  // 2: signer.KeyStatus.lock_state:type_name -> signer.LockState
	6,  // 3: signer.StatusResponse.keys:type_name -> signer.KeyStatus
	11, // 4: signer.NewKeysResponse.results:type_name -> signer.NewKeyPerKeyResult
	1,  // 5: signer.DeleteKeysResponse.results:type_name -> signer.PerKeyResult
	2,  // 6: signer.Request.unlock:type_name -> signer.UnlockRequest
	4,  // 7: signer.Request.lock:type_name -> signer.LockRequest
	7,  // 8: signer.Request.status:type_name -> signer.StatusRequest
	9,  // 9: signer.Request.sign:type_name -> signer.SignRequest
	12, // 10: signer.Request.new_keys:type_name -> signer.NewKeysRequest
	14, // 11: signer.Request.logs:type_name -> signer.LogsRequest
	16, // 12: signer.Request.init_master:type_name -> signer.InitMasterRequest
	17, // 13: signer.Request.init_info:type_name -> signer.InitInfoRequest
	19, // 14: signer.Request.set_level:type_name -> signer.SetLevelRequest
	20, // 15: signer.Request.delete_keys:type_name -> signer.DeleteKeysRequest
	3,  // 16: signer.Response.unlock:type_name -> signer.UnlockResponse
	5,  // 17: signer.Response.lock:type_name -> signer.LockResponse
	8,  // 18: signer.Response.status:type_name -> signer.StatusResponse
	10, // 19: signer.Response.sign:type_name -> signer.SignResponse
	13, // 20: signer.Response.new_key:type_name -> signer.NewKeysResponse
	15, // 21: signer.Response.logs:type_name -> signer.LogsResponse
	18, // 22: signer.Response.init_info:type_name -> signer.InitInfoResponse
	21, // 23: signer.Response.delete_keys:type_name -> signer.DeleteKeysResponse
	22, // 24: signer.Response.ok:type_name -> signer.Ok
	23, // 25: signer.Response.error:type_name -> signer.Error
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_signer_proto_init() }
func file_signer_proto_init() {
	if File_signer_proto != nil {
		return
	}
	file_signer_proto_msgTypes[23].OneofWrappers = []any{
		(*Request_Unlock)(nil),
		(*Request_Lock)(nil),
		(*Request_Status)(nil),
		(*Request_Sign)(nil),
		(*Request_NewKeys)(nil),
		(*Request_Logs)(nil),
		(*Request_InitMaster)(nil),
		(*Request_InitInfo)(nil),
		(*Request_SetLevel)(nil),
		(*Request_DeleteKeys)(nil),
	}
	file_signer_proto_msgTypes[24].OneofWrappers = []any{
		(*Response_Unlock)(nil),
		(*Response_Lock)(nil),
		(*Response_Status)(nil),
		(*Response_Sign)(nil),
		(*Response_NewKey)(nil),
		(*Response_Logs)(nil),
		(*Response_InitInfo)(nil),
		(*Response_DeleteKeys)(nil),
		(*Response_Ok)(nil),
		(*Response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signer_proto_goTypes,
		DependencyIndexes: file_signer_proto_depIdxs,
		EnumInfos:         file_signer_proto_enumTypes,
		MessageInfos:      file_signer_proto_msgTypes,
	}.Build()
	File_signer_proto = out.File
	file_signer_proto_goTypes = nil
	file_signer_proto_depIdxs = nil
}
