name: build-host
description: Build the host application for the specified OS and architecture

inputs:
  toolchain:
    description: 'The zig target triple for the toolchain to use'
    required: true
  artifact-id:
    description: 'The ID of the artifact to build'
    required: true
  goos:
    description: 'The GOOS value for the build'
    required: true
  goarch:
    description: 'The GOARCH value for the build'
    required: true
  libusb-host:
    description: 'The libusb host target'
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: '>=1.26.0'

  - uses: mlugg/setup-zig@v2
    with:
      version: '0.15.2'

  - name: Create build dir
    shell: bash
    run: mkdir -p build

  - name: autogen libusb (linux)
    shell: bash
    env:
      CC: zig cc -target ${{ inputs.toolchain }}
      CXX: zig c++ -target ${{ inputs.toolchain }}
    working-directory: ${{ github.workspace }}/libs/libusb
    run: ./autogen.sh --disable-udev --host=${{ inputs.libusb-host }}

  - name: configure libusb (linux)
    shell: bash
    env:
      CC: zig cc -target ${{ inputs.toolchain }}
      CXX: zig c++ -target ${{ inputs.toolchain }}
      INSTALL_DIR: ${{ github.workspace }}/libs/.install
    working-directory: ${{ github.workspace }}/libs/libusb
    run: ./configure --prefix=$INSTALL_DIR --enable-udev=no --enable-shared=no --disable-dependency-tracking --host=${{ inputs.libusb-host }}

  - name: make libusb
    shell: bash
    working-directory: ${{ github.workspace }}/libs/libusb
    run: make install
    
  - name: Build host (linux)
    shell: bash
    env:
      CC: zig cc -target ${{ inputs.toolchain }}
      CXX: zig c++ -target ${{ inputs.toolchain }}
      GOOS: ${{ inputs.goos }}
      GOARCH: ${{ inputs.goarch }}
      CGO_ENABLED: 1
      PKG_CONFIG_PATH: "${{ github.workspace }}/libs/.install/lib/pkgconfig"
    run: |
       go build -ldflags='-s -w -extldflags "-I${{ github.workspace }}/libs/.install/include/libusb-1.0 -L${{ github.workspace }}/libs/.install/lib/ -lusb-1.0 -static"' -trimpath -o ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }} ./app/host

  - uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact-id }}
      path: ./build/tezsign-host-${{ inputs.goos }}-${{ inputs.goarch }}
      retention-days: 1
