BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tezsign"
BBFILE_PATTERN_meta-tezsign = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tezsign = "10"

LAYERDEPENDS_meta-tezsign = "core"
LAYERSERIES_COMPAT_meta-tezsign = "whinlatter scarthgap"

# PACKAGECONFIG:remove:pn-systemd = " \
#     networkd resolved timesyncd nss-resolve \
#     acl bluez dbus elfutils idn locale localed \
#     vconsole machined hibernate myhostname \
#     manpages polkit seccomp xkbcommon \
# "

# IMAGE_LINGUAS = ""
# FORCE_RO_REMOVE = "1"
# NO_RECOMMENDATIONS = "1"

BBFILES_DYNAMIC += " \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/recipes-bsp/*/*.bbappend \
    rockchip:${LAYERDIR}/dynamic-layers/rockchip/recipes-bsp/*/*.bbappend \
"