name: "Build Release"

on:
  push:
  pull_request:

jobs:
    build-gadget:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - kas_file: "rpi4.yml"
                      release_name: "rpi4"
                      image_flavour: "rpi4"
                      gadget_goarm64: "v8.0"
                      gadget_cgo_cflags: "-march=armv8-a -mcpu=cortex-a72 -D__BLST_PORTABLE__ -O2"
                    - kas_file: "rpi4-dev.yml"
                      release_name: "rpi4_dev"
                      image_flavour: "rpi4"
                      gadget_goarm64: "v8.0"
                      gadget_cgo_cflags: "-march=armv8-a -mcpu=cortex-a72 -D__BLST_PORTABLE__ -O2"
                    - kas_file: "rpi0-2w.yml"
                      release_name: "rpi0_2w"
                      image_flavour: "rpi0_2w"
                      gadget_goarm64: "v8.0"
                      gadget_cgo_cflags: "-march=armv8-a -mcpu=cortex-a53 -D__BLST_PORTABLE__ -O2"
                    - kas_file: "rpi0-2w-dev.yml"
                      release_name: "rpi0_2w_dev"
                      image_flavour: "rpi0_2w"
                      gadget_goarm64: "v8.0"
                      gadget_cgo_cflags: "-march=armv8-a -mcpu=cortex-a53 -D__BLST_PORTABLE__ -O2"
                    - kas_file: "radxa-zero3.yml"
                      release_name: "radxa_zero3"
                      image_flavour: "radxa_zero3"
                      gadget_goarm64: "v8.2"
                      gadget_cgo_cflags: "-march=armv8.2-a+crypto -mcpu=cortex-a55 -O2"
                    - kas_file: "radxa-zero3-dev.yml"
                      release_name: "radxa_zero3_dev"
                      image_flavour: "radxa_zero3"
                      gadget_goarm64: "v8.2"
                      gadget_cgo_cflags: "-march=armv8.2-a+crypto -mcpu=cortex-a55 -O2"
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Build ${{ matrix.release_name }} image
              uses: ./.github/template/build-yocto
              with:
                kas-file: ${{ matrix.kas_file }}
                release-name: ${{ matrix.release_name }}
                image-flavour: ${{ matrix.image_flavour }}
                gadget-goarm64: ${{ matrix.gadget_goarm64 }}
                gadget-cgo-cflags: ${{ matrix.gadget_cgo_cflags }}

    build-updater:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version-file: go.mod

            - name: Create build dir
              run: mkdir -p build

            - name: Build tezsign updater (Linux aarch64)
              env:
                GOOS: linux
                GOARCH: arm64
              run: |
                  go build -ldflags='-s -w -extldflags "-static"' -trimpath -o ./build/tezsign_updater_linux_arm64 ./tools/updater
            
            - name: Build tezsign updater (Linux amd64)
              env:
                GOOS: linux
                GOARCH: amd64
              run: |
                  go build -ldflags='-s -w -extldflags "-static"' -trimpath -o ./build/tezsign_updater_linux_amd64 ./tools/updater

            - name: Build tezsign updater (macos arm64)
              env:
                GOOS: darwin
                GOARCH: arm64
              run: |
                  go build -ldflags='-s -w -extldflags "-static"' -trimpath -o ./build/tezsign_updater_macos_arm64 ./tools/updater

            - name: Upload tezsign_updater artifact
              uses: actions/upload-artifact@v7
              with:
                name: tezsign_updater
                path: ./build/*
                retention-days: 1

    build-host-linux-amd64:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
            with:
                fetch-depth: 0

          - uses: ./.github/template/build-host-linux
            with:
              toolchain: x86_64-linux-musl
              artifact-id: tezsign-host-linux-amd64
              goos: linux
              goarch: amd64
              libusb-host: x86_64-linux-musl

    build-host-linux-arm64:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
            with:
                fetch-depth: 0

          - uses: ./.github/template/build-host-linux
            with:
              toolchain: aarch64-linux-musl
              artifact-id: tezsign-host-linux-arm64
              goos: linux
              goarch: arm64
              libusb-host: aarch64-linux-musl

    build-host-macos-amd64:
        runs-on: macos-15-intel
        steps:
          - uses: actions/checkout@v5
            with:
                fetch-depth: 0

          - uses: ./.github/template/build-host-macos
            with:
              goos: macos
              goarch: amd64
              artifact-id: tezsign-host-macos-amd64
              libusb-host: x86_64-darwin-none

    build-host-macos-arm64:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v5
            with:
                fetch-depth: 0

          - uses: ./.github/template/build-host-macos
            with:
              goos: macos
              goarch: arm64
              artifact-id: tezsign-host-macos-arm64
              libusb-host: aarch64-darwin-none

    # build-host-windows-amd64:
    #     runs-on: windows-latest
    #     steps:
    #       - uses: actions/checkout@v5
    #         with:
    #             fetch-depth: 0

    #       - uses: ./.github/template/build-host-windows
    #         with:
    #           toolchain: x86_64-windows-gnu
    #           artifact-id: tezsign-host-windows-amd64
    #           goos: windows
    #           goarch: amd64
    #           libusb-host: x64-mingw-static

    # build-host-windows-arm64:
    #     runs-on: windows-11-arm
    #     steps:
    #       - uses: actions/checkout@v5
    #         with:
    #             fetch-depth: 0

    #       - uses: ./.github/template/build-host-windows
    #         with:
    #           toolchain: aarch64-windows-gnu
    #           artifact-id: tezsign-host-windows-arm64
    #           goos: windows
    #           goarch: arm64
    #           libusb-host: arm64-mingw-static

    publish:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
          contents: write
        needs: 
          - build-gadget
          - build-host-linux-amd64
          - build-host-linux-arm64
          - build-host-macos-amd64
          - build-host-macos-arm64
          # - build-host-windows-amd64
          # - build-host-windows-arm64
          - build-updater
        steps:
          - uses: actions/checkout@v5

          - name: create release dir
            run: mkdir ./release

          - uses: actions/download-artifact@v7
            with:
              path: ./release
              merge-multiple: true

          - name: Set date
            id: release_date
            run: echo "date=$(date +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"
            
          - name: publish
            uses: ncipollo/release-action@v1
            with:
              artifacts: ./release/*
              tag: release-${{ steps.release_date.outputs.date }}
              commit: ${{ github.sha }}
              prerelease: true
